modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="frontline"
version="0.1.0"
displayName="Frontline"
description='''Военная тематика: мешки с песком, медицина, бинокль, рация и волны мобов.'''

[[dependencies.frontline]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.frontline]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
